spring:
  datasource:
    url: jdbc:hsqldb:mem:db
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.HSQLDialect
    show-sql: true
